version: "3.3"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=user12345
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=superchat
    volumes:
      - pgdb:/var/lib/postgresql/data
  superchat:
    image: konnovk/superchat:main
    restart: always
    environment:
      - CHAT_DB_USER=user12345
      - CHAT_DB_PASSWORD=12345
      - CHAT_DB_HOST=db
      - CHAT_DB_PORT=5432
      - CHAT_DB_NAME=superchat
      - REDIS_ADDR=cache:6379
  cache:
    image: redis:latest
    restart: always
    command: redis-server
    volumes:
      - cache:/data
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs/nginx:/var/log/nginx
      # TODO redo paths to static files
volumes:
  pgdb:
  cahce:
