definitions:
  entity.ChatResponse:
    properties:
      creator:
        type: string
      id:
        type: integer
      lastMessage:
        items:
          $ref: '#/definitions/entity.MessageResponse'
        type: array
      tags:
        items:
          type: string
        type: array
      title:
        type: string
      ttl:
        type: integer
    type: object
  entity.CreateChatRequest:
    properties:
      author:
        type: string
      tags:
        items:
          type: string
        type: array
      title:
        type: string
      ttl:
        type: integer
    type: object
  entity.MessageResponse:
    properties:
      message:
        type: string
      sender:
        type: string
      sentAt:
        type: string
    type: object
  entity.SendMessageRequest:
    properties:
      message:
        type: string
      sender:
        type: string
    type: object
info:
  contact: {}
paths:
  /chat:
    post:
      consumes:
      - application/json
      description: Create new chat
      parameters:
      - description: Create chat
        in: body
        name: chat
        required: true
        schema:
          $ref: '#/definitions/entity.CreateChatRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.ChatResponse'
        "400":
          description: ""
        "404":
          description: ""
        "500":
          description: ""
      summary: Create new chat
      tags:
      - chat
  /chat/{id}/message:
    get:
      description: Get all messages in chat by chat id
      parameters:
      - description: Chat ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.MessageResponse'
            type: array
        "400":
          description: ""
        "404":
          description: ""
        "500":
          description: ""
      summary: Get all messages in chat
      tags:
      - chat
    post:
      description: Send message to chat by chat id
      parameters:
      - description: Chat ID
        in: path
        name: id
        required: true
        type: integer
      - description: Send message
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/entity.SendMessageRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.MessageResponse'
        "400":
          description: ""
        "404":
          description: ""
        "500":
          description: ""
      summary: Send message to chat
      tags:
      - chat
  /chat/active:
    get:
      description: Get all active chats at the moment
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.ChatResponse'
            type: array
        "400":
          description: ""
        "404":
          description: ""
        "500":
          description: ""
      summary: Get active chats
      tags:
      - chat
swagger: "2.0"
